---
vmDefaults:
  accessMode: ReadWriteMany
  cloudinitsecret: secret/data/global/cloud-init
  cores: 1
  count: 1
  extraLabels:
    drprotection: true
  flavor: medium
  machineType: pc-q35-rhel8.4.0
  memory: 4Gi
  os: rhel9
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  publishService: true
  sockets: 1
  sshpubkeyfield: publickey
  sshsecret: secret/data/global/vm-ssh
  storage: 30Gi
  storageClassName: ocs-storagecluster-ceph-rbd-virtualization
  template: rhel9-server-medium
  threads: 1
  volumeMode: Block
  workload: server
vms:
  edgenode:
    count: 4
    role: node
waitForMetalNode: false
