# Generated by patternizer
# This Makefile includes the common pattern targets from Makefile-common
# You can add custom targets above or below the include line
include Makefile-common

TARGET_CLUSTERGROUP ?= odf

.PHONY: install-byoc
install-byoc: ramen-prereq pattern-install ## Installs the pattern onto a cluster (Loads secrets as well if configured)

.PHONY: ramen-prereq
ramen-prereq: ## Check if values.byoc false do nothing, else run the precheck against clusters accessed from values-secrets
	echo "Running precheck for ramendr"
	cd ansible && ansible-playbook -i hosts $(EXTRA_ARGS) $(EXTRA_VARS) playbooks/validate_byoc.yml

.PHONY: run-ci-tests
run-ci-tests: ## Run CI interop tests (called by the pipeline interop-test task)
	cd tests/ci && \
	  mkdir -p .results && \
	  pytest -lv test_$(TARGET_CLUSTERGROUP).py \
	    --junit-xml .results/test_$(TARGET_CLUSTERGROUP).xml
