---
clusterGroup:
  name: hub
  isHubCluster: true
  namespaces:
    open-cluster-management:
    open-cluster-management-observability:
    vault:
    golang-external-secrets:
    regional-dr:
    openshift-dr-system:
    openshift-dr-ops:
    policies:
    openshift-storage:
  projects:
  - hub
  - opp
  sharedValueFiles:
  - /overrides/values-{{ $.Values.global.clusterPlatform }}.yaml
  argoCD:
    resourceTrackingMethod: annotation
  subscriptions:
    acm:
      channel: release-2.15
      name: advanced-cluster-management
      namespace: open-cluster-management
    odf-multicluster-orchestrator:
      name: odf-multicluster-orchestrator
      namespace: openshift-operators
    openshift-data-foundation:
      name: odf-operator
      namespace: openshift-storage
  applications:
    acm:
      chart: acm
      chartVersion: 0.1.*
      ignoreDifferences:
      - group: internal.open-cluster-management.io
        kind: ManagedClusterInfo
      name: acm
      namespace: open-cluster-management
      project: hub
    ensure-openshift-console-plugins:
      chart: ensure-openshift-console-plugins
      chartVersion: 0.1.*
      extraValueFiles:
      - $patternref/overrides/values-console-plugins-hub.yaml
      name: ensure-openshift-console-plugins
      namespace: openshift-console
      project: opp
    golang-external-secrets:
      chart: golang-external-secrets
      chartVersion: 0.2.*
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: hub
    opp-policy:
      annotations:
        argocd.argoproj.io/sync-wave: '5'
      chartVersion: main
      extraValueFiles:
      - /overrides/values-cluster-names.yaml
      ignoreDifferences:
      - group: operators.openshift.io
        jsonPointers:
        - /spec/plugins
        kind: Console
      name: opp-policy
      namespace: openshift
      path: .
      project: opp
      repoURL: https://github.com/validatedpatterns/opp-policy-chart.git
      syncPolicy:
        automated: {}
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
          limit: 20
        syncOptions:
        - syncTimeout=3600s
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - RespectIgnoreDifferences=true
        - ServerSideApply=true
    opp-odf:
      annotations:
        argocd.argoproj.io/sync-wave: '6'
      extraValueFiles:
      - /overrides/values-cluster-names.yaml
      name: opp-odf
      namespace: openshift
      path: charts/hub/opp-odf
      project: opp
      syncPolicy:
        automated: {}
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
          limit: 20
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
    rdr:
      annotations:
        argocd.argoproj.io/sync-wave: '10'
      chartVersion: main
      extraValueFiles:
      - /overrides/values-cluster-names.yaml
      - /overrides/values-egv-dr.yaml
      - $patternref/overrides/values-rdr-storage-odf.yaml
      ignoreDifferences:
      - group: internal.open-cluster-management.io
        kind: ManagedClusterInfo
      name: regional-dr
      namespace: regional-dr
      path: .
      project: opp
      repoURL: https://github.com/validatedpatterns/regionaldr-with-virt-chart.git
      syncPolicy:
        automated: {}
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
          limit: 60
        syncOptions:
        - RespectIgnoreDifferences=true
    rdr-odf:
      annotations:
        argocd.argoproj.io/sync-wave: '11'
      extraValueFiles:
      - /overrides/values-cluster-names.yaml
      name: rdr-odf
      namespace: regional-dr
      path: charts/hub/rdr-odf
      project: opp
      syncPolicy:
        automated: {}
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
          limit: 60
        syncOptions:
        - RespectIgnoreDifferences=true
    odf:
      chart: openshift-data-foundations
      chartVersion: 0.2.*
      extraValueFiles:
      - $patternref/overrides/values-odf-chart.yaml
      name: odf
      namespace: openshift-storage
      project: opp
      syncOptions:
      - CreateNamespace=true
    vault:
      chart: hashicorp-vault
      chartVersion: 0.1.*
      name: vault
      namespace: vault
      project: hub
  imperative:
    jobs: []
    verbosity: -vvv
  managedClusterGroups:
    resilient:
      acmlabels:
      - name: clusterGroup
        value: resilient
      helmOverrides:
      - name: clusterGroup.isHubCluster
        value: 'false'
      name: resilient
